### ISSUE TITLE
robot is not going strait forward

### ISSUE THREAD

**Issue by fly72t** [bjpirt/mirobot-pcb#4]
I have an issue that the robot (brand new) is not going strait forward if he receives a command of move into that direction. He always turns some degrees into the same direction. It seems that the stepper motor is not getting or execute the same steps on each site. The wheel is not blocker since everything is correct if we needs to go backwards and he is doing that straight.
Is that a soldering error on the PCB or is it a defect in the stepper engine (what I think).

Thanks Hendrik

**Comment by bjpirt** [comment]
The best place for troubleshooting help like this is over on [Google Groups](https://groups.google.com/forum/#!forum/mirobot), but since we're here :-) ...

First take a look at the troubleshooting guide: http://mirobot.io/build/v1/troubleshooting/

Try to isolate whether the motor is faulty by swapping them round and seeing if the same motor doesn't move. If it's not the motor then it's most likely to be the soldering on the Arduino.
Cheers,
Ben
